baseURL = "https://jexsaga.github.io/NinaAndJess_XRBlog/"
languageCode = "en-us"
title = "Nina and Jess XR Blog"
theme = "ananke"

[params]
  recent_posts_number = 10



[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true