baseURL = "https://jexsaga.github.io/NinaAndJess_XRBlog/"
languageCode = "en-us"
title = "Nina and Jess XR Blog"
theme = "ananke"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
